import blog_ca_1_image from '../images/blog_ca_1_img.jpeg';
import blog_ca_2_image from '../images/blog_ca_2_img.jpeg';
import blog_ca_3_image from '../images/blog_ca_3_img.jpeg';
import blog_ca_4_image from '../images/blog_ca_4_img.jpeg';

export const ProjectsData = [
    {
        "id": "_00",
        "city": "Nagpur",
        "cover_img": blog_ca_1_image,
        "client": "C.A. Jadwani",
        "cover_title": "CA. Project",
        "location": "something near somewhere",
        "title": "<h1>CA. Commercial Project</h1>",
        "project_img": [blog_ca_1_image, blog_ca_2_image, blog_ca_3_image, blog_ca_4_image],
        'title_text': 'CA. Commercial Project',
        'completion_year': '2019',
    },
    {
        "id": "_01",
        "city": "Nagpur",
        "cover_img": blog_ca_1_image,
        "client": "C.A. Jadwani",
        "author": "Arti Mahajan",
        "cover_title": "Clinic Project",
        "location": "something near somewhere",
        "title": "<h1>CA. Commercial Project</h1>",
        "project_id": "proj_01",
        'title_text': 'CA. Commercial Project',
        'completion_year': '2019',
    },
    {
        "id": "_02",
        "city": "Nagpur",
        "cover_img": blog_ca_1_image,
        "client": "C.A. Jadwani",
        "author": "Arti Mahajan",
        "cover_title": "Lickster's Ice-cream",
        "location": "something near somewhere",
        "title": "<h1>CA. Commercial Project</h1>",
        "project_id": "proj_01",
        'title_text': 'CA. Commercial Project',
        'completion_year': '2019',
    },
    {
        "id": "_03",
        "city": "Nagpur",
        "cover_img": blog_ca_1_image,
        "client": "C.A. Jadwani",
        "author": "Arti Mahajan",
        "cover_title": "CA. Commercial Project",
        "location": "something near somewhere",
        "title": "<h1>CA. Commercial Project</h1>",
        "project_id": "proj_01",
        'title_text': 'CA. Commercial Project',
        'completion_year': '2019',
    },
    {
        "id": "_04",
        "city": "Nagpur",
        "cover_img": blog_ca_1_image,
        "client": "C.A. Jadwani",
        "author": "Arti Mahajan",
        "cover_title": "CA. Commercial Project",
        "location": "something near somewhere",
        "title": "<h1>CA. Commercial Project</h1>",
        "project_id": "proj_01",
        'title_text': 'CA. Commercial Project',
        'completion_year': '2019',
    },
]